name: API Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: PHPUnit Test
    runs-on: ubuntu-latest

    steps:
      # ?????????????
      - uses: actions/checkout@v4

      # ????Web????????????????
      - run: |
          php -S localhost:8000 -t src &
          sleep 5

      # Composer???????????????????
      - uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          args: '--no-progress --prefer-dist'

      # PHPUnit???
      - uses: php-actions/phpunit@v3
        with:
          php_version: '8.3'
          test_suffix: './tests/TodoTest.php'
